### ISSUE TITLE
deep linking doesn't work

### ISSUE THREAD

**Issue by Nek** [vishvish/BirdBase#1]
and gives this error
[Fault] exception, information=ArgumentError: Error #1063: Argument count mismatch on com.asual.swfaddress::SWFAddress$/_setValue(). Expected 2, got 1.
at Function/http://adobe.com/AS3/2006/builtin::apply()
at flash.external::ExternalInterface$/_callIn()
at Function/<anonymous>()

**Comment by vishvish** [comment]
I have seen this issue with SWFAddress. I am using the latest dev version of swfaddress - 2.5 - what are you using? I'm not sure if I'm including this dependency or not...

(I should really write this up in a post.)

**Comment by vishvish** [comment]
Grab the latest SWFAddress source here:

https://swfaddress.svn.sourceforge.net/svnroot/swfaddress/trunk/swfaddress/src/

**Comment by Nek** [comment]
I've got version 2.4
Thanks for the link. I'll try to upgrade it.
I think you should put a ready to use html template of the release folder with all the needed js libs into downloads.
It will help a lot to all the early adopters!

**Comment by Nek** [comment]
Hooray!!! 2.5 fixes the problem.

**Comment by vishvish** [comment]
The Birdbase Demo should be up-to-date now. I'll update Birdbase soon and make a note on the blog. Cheers for reporting.
